# Generated by Django 5.1.3 on 2024-11-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JourneySegment',
        ),
    ]
