services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn dvmtask2.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles
      - ./mediafiles:/usr/src/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dvmtask2
      POSTGRES_USER: dvmtask2
      POSTGRES_PASSWORD: test@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dvmtask2"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_data:
  media_data:
  postgres_data:
