# Generated by Django 5.1.3 on 2024-11-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.day')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_seats', models.IntegerField(default=0)),
                ('total_seats', models.IntegerField(default=0)),
                ('available_seats', models.IntegerField(default=0)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.date')),
            ],
        ),
        migrations.CreateModel(
            name='JourneySeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.journey')),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.seatcategory')),
            ],
        ),
        migrations.CreateModel(
            name='JourneySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('journey_duration', models.DurationField(blank=True, null=True)),
                ('segment_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.journey')),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_segments', to='railways.station')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_segments', to='railways.station')),
            ],
        ),
        migrations.CreateModel(
            name='HaltStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('is_datechanging', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.station')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(unique=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('journey_duration', models.DurationField(blank=True, null=True)),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_trains', to='railways.station')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_trains', to='railways.station')),
                ('halts', models.ManyToManyField(related_name='halts', through='railways.HaltStation', to='railways.station')),
                ('running_days', models.ManyToManyField(to='railways.day')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.train'),
        ),
        migrations.AddField(
            model_name='haltstation',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.train'),
        ),
        migrations.CreateModel(
            name='TrainSeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.seatcategory')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.train')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='seat_categories',
            field=models.ManyToManyField(through='railways.TrainSeatCategory', to='railways.seatcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='haltstation',
            unique_together={('station', 'order', 'train')},
        ),
    ]
