# Generated by Django 5.1.3 on 2024-11-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0003_passenger_remove_journey_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='journey_seat_categories',
            field=models.ManyToManyField(related_name='journeys', to='railways.journeyseatcategory'),
        ),
    ]
