# Generated by Django 5.1.3 on 2024-11-20 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0002_delete_journeysegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('is_child', models.BooleanField(default=False)),
                ('is_senior', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='journey',
            name='date',
        ),
        migrations.RemoveField(
            model_name='train',
            name='journey_duration',
        ),
        migrations.AddField(
            model_name='journey',
            name='arrival_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_journeys', to='railways.date'),
        ),
        migrations.AddField(
            model_name='journey',
            name='departure_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_journeys', to='railways.date'),
        ),
        migrations.AddField(
            model_name='train',
            name='travel_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.journey')),
                ('passengers', models.ManyToManyField(to='railways.passenger')),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.journeyseatcategory')),
            ],
        ),
    ]
